### ISSUE TITLE
API in Proxy for Multi Factor Authentication in Desktop Client

### ISSUE THREAD

**Issue by teon** [DefGuard/client#104]
1. Proxy will **expose user MFA endpoints** from core by connecting with GRPC to defguard. 
2. Defuard client before connect will need to go through MFA exactly the same as after doing login on the web.
3. After successful MFA on client - the client receives a unique **PSK KEY** for this device, the gateway receives action of adding a new PEER with this PSK key.

In VPN Settings we need a checkbox **Require MFA to connect to this Location** (enabled by default).

Add **rate limit** - 5/min && (if possible) after that 1min brake.

**Comment by teon** [comment]
@4lb we need to talk it through from design point of view

**Comment by teon** [comment]
Agreed on duplicate core UI

**Comment by przemyslaw** [comment]
MVP - one method for MFA

**Comment by wojcik91** [comment]
TODO:

- update location setup screen to include MFA checkbox
- update protos & proxy to expose auth methods from core
  - login (username + password) 
  - TOTP/email code auth
- update location data stored in client
- login flow in client (on tunnel connect)
  - step 1: username + password login
  - step 2: MFA method choice
  - step 3: MFA code

**Comment by teon** [comment]
Design -> https://www.figma.com/file/uoFcgpOuVWa6g7tvKwB52o/defguard?type=design&node-id=3963%3A12460&mode=design&t=8S3WzxGSIpjnMb74-1

Sekcja: GH-https://github.com/DefGuard/client/issues/128

**Comment by wojcik91** [comment]
Rate limiting moved to a dedicated task: https://github.com/DefGuard/proxy/issues/45
