### ISSUE TITLE
Window with white background and blank

### ISSUE THREAD

**Issue by edgan** [DefGuard/client#132]
I downloaded the version 0.1.1 from the releases page, extracted it, and ran it. All I get is a window with a white background and it is blank. The tray icon works, and can be used to close it.

If I right click and select reload I see this error in the terminal window.

```
Asset `client` not found; fallback to client.html
```

It seems to be an issue with Xorg, since it works on Wayland.

Doesn't work:
Fedora 39
Xorg with Nvidia graphics
akmod-nvidia-545.29.06-1.fc39.x86_64
kernel-6.6.6-200.fc39.x86_64
xorg-x11-server-Xorg-1.20.14-28.fc39.x86_64

Works:
Fedora 39
Wayland with Nvidia graphics
akmod-nvidia-545.29.06-1.fc39.x86_64
kernel-6.6.6-200.fc39.x86_64

Works:
Fedora 39
Wayland with Intel graphics
kernel-6.6.6-200.fc39.x86_64

**Comment by edgan** [comment]
Also seems to work with XWayland when using `GDK_BACKEND=x11`.

**Comment by edgan** [comment]
Running `yarn tauri dev` has the same outcome. Yet if I go to http://localhost:3000/client in a browser I see the ui. 

Running `WEBKIT_DISABLE_DMABUF_RENDERER=1 defguard-client` seems to make it work.

Downgrading webkit2gtk4.0 also fixes it.

Downgrade packages from Fedora 38 for Fedora 39:
```
wget https://mirrors.kernel.org/fedora/releases/38/Everything/x86_64/os/Packages/w/webkit2gtk4.0-2.40.0-2.fc38.x86_64.rpm
wget https://mirrors.kernel.org/fedora/releases/38/Everything/x86_64/os/Packages/w/webkit2gtk4.0-devel-2.40.0-2.fc38.x86_64.rpm
wget https://mirrors.kernel.org/fedora/releases/38/Everything/x86_64/os/Packages/j/javascriptcoregtk4.0-2.40.0-2.fc38.x86_64.rpm
wget https://mirrors.kernel.org/fedora/releases/38/Everything/x86_64/os/Packages/j/javascriptcoregtk4.0-devel-2.40.0-2.fc38.x86_64.rpm
rpm -U --oldpackage webkit2gtk4.0-2.40.0-2.fc38.x86_64.rpm webkit2gtk4.0-devel-2.40.0-2.fc38.x86_64.rpm javascriptcoregtk4.0-2.40.0-2.fc38.x86_64.rpm javascriptcoregtk4.0-devel-2.40.0-2.fc38.x86_64.rpm
```

Links:
https://bugs.archlinux.org/task/79783
https://github.com/eclipse-platform/eclipse.platform.swt/issues/843
https://www.phoronix.com/news/WebKitGTK-DMA-BUF-Rendering
https://old.reddit.com/r/Fedora/comments/173461a/does_anyone_know_why_the_option_for_me_to_log_in/
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1932089.html

**Comment by teon** [comment]
@edgan thank you for your analysis and comments. We are working heavy on the next version of the client with some important UI changes and functionalities. After we release it (hopefully next week) we will dive into this issue.
