### ISSUE TITLE
Desktop Client doesn't show ALL Allowed IPs

### ISSUE THREAD

**Issue by teon** [DefGuard/client#165]
According to design:

![Image](https://github.com/DefGuard/client/assets/139682/8c9bad87-3f9d-4ab2-a503-b059f52cc72b)

Allowed Ips looks like ^^^^.
Our allowed IPs has several ips, but only **one** is shown in VPN details:

![Image](https://github.com/DefGuard/client/assets/139682/6cced093-8a41-4431-af07-b29bc28f727a)

**Comment by dzania** [comment]
Closed by #167
