### ISSUE TITLE
Can't Add IPv6 Address as Address

### ISSUE THREAD

**Issue by Rishi556** [DefGuard/client#191]
Tried to add my config and got an issue on the address section:

<img width="254" alt="image" src="https://github.com/DefGuard/client/assets/10539109/47d2e21b-1562-44fa-947e-46f276439831">

It fails wether I have just the v6 address, a v6 and a v4 address.

<img width="323" alt="image" src="https://github.com/DefGuard/client/assets/10539109/6200318e-6c31-43b9-aed3-e7d784e96540">

Only way I got it to work was by removing the IPv6 address:

<img width="231" alt="image" src="https://github.com/DefGuard/client/assets/10539109/1f7b6d7c-5325-4d6e-9c52-3922fbbc72f2">

**Comment by Rishi556** [comment]
Looks like the same thing happens in the DNS section and the VPN server address section: 

<img width="300" alt="image" src="https://github.com/DefGuard/client/assets/10539109/a4a500ce-2499-4e3c-8f9f-b64dd6c9d5bb">

**Comment by teon** [comment]
Oh, we need to fix the validation. Will do next sprint.

**Comment by Rishi556** [comment]
https://github.com/DefGuard/client/pull/197 seems to have fixed part of the issue. I still see it not accepting both IPv6 and IPv4 address under the address section at once. I'm importing the same file that I use on the native WG client.

No errors when initially importing:
<img width="348" alt="image" src="https://github.com/DefGuard/client/assets/10539109/0cdd4d25-35c6-4062-a683-f751eeb363c3">

After hitting submit:
<img width="285" alt="image" src="https://github.com/DefGuard/client/assets/10539109/620e1af2-80d9-487b-92b1-9effe442c325">


Using just the IPv6 address does work, seems to have issues with both a v4 and v6 address at once. I guess that it's truly a different issue at hand though.

Here's a sanitized version of the config file:

```
[Interface]
PrivateKey = ABC123
Address = 10.0.0.1/32, 2600:db8::1/128
DNS = 2606:4700:4700::1111

[Peer]
PublicKey = ABC123
PresharedKey = ABC123
AllowedIPs = ::0/0, 0.0.0.0/0
Endpoint = [2600:db8::2]:443
```
