### ISSUE TITLE
Prepare signed windows binaries

### ISSUE THREAD

**Issue by teon** [DefGuard/client#202]
Our CI/build is prepared for signing, but we need to modify Windows build workflow to:

1. Sign the **MSI** produced (wireguard included and bundled was already signed)
2. After exe is generated with defguard MSI (signed) and wireguard (signed) - we need to sign the EXE
3. And release this signed exe

**Comment by 0rbiter** [comment]
The current 0.4.0 windows client is not signed. Will you fix that?

**Comment by teon** [comment]
@0rbiter it is signed. Can you showcase on a screen what you mean?

**Comment by 0rbiter** [comment]
It's the "windows protected you from running this software" SmartScreen warning. I might have mistaken this for signing a driver, it's just the Microsoft SmartScreen filter.
Apparently this can be prevented by submitting the application to Microsoft for malware analysis? EV or standard code signing certificates etc.
It's really irritating to users when rolling out that they receive this message and makes them question the security of the software.
![protected](https://github.com/user-attachments/assets/f9df081a-4cdc-4fb9-9577-06d241f61724)

**Comment by teon** [comment]
We did that the day we released the version. Microsoft….

**Comment by 0rbiter** [comment]
Seems to work fine now, probably just took a few days for the update to come through
