### ISSUE TITLE
macOS client resizes window unexpectedly

### ISSUE THREAD

**Issue by tomasbedrich** [DefGuard/client#207]
After each launch on an application (when it was not running before) the client opens the window and _resizes on its own_. Likely it tries to maximize to fill entire screen, but instead its top left corner remains in place -> the window overflows from the screen.

My preference is for client to remember the last window position.

**Comment by nhymxu** [comment]
look like they fixed size here 👎 
https://github.com/DefGuard/client/blob/abff2c7ceb311cb2d2aed3fbd82eb7abc2153db1/src-tauri/tauri.conf.json#L98-L104
