### ISSUE TITLE
Normalize interface name in Wireguard Tunnel mode

### ISSUE THREAD

**Issue by syphernl** [DefGuard/client#216]
The Defguard client uses the Tunnel Name to generate an interface name. This works fine as long as there are no special characters in the name.

* Works: `AWS`
* Does not work: `AWS (Test)`

The client should either use a cleaned up Tunnel Name as interface name (e.g. remove all unsupported characters) or should disallow any illegal characters in the Tunnel Name.

**Comment by teon** [comment]
Only **letters with no spaces and numbers** should be allowed for device name.
