### ISSUE TITLE
Release 0.3.0 desktop clients

### ISSUE THREAD

**Issue by teon** [DefGuard/client#224]
Release notes:
-  Windows client has code-signed binaries!
- Windows does not report the binary as malicious software #228 
- VPN server can now be a domain name and not only IP address #213 
- Added posibility to define Pre-shared key in Wireguard Tunnels #211 
- On Linux tunnel interface has a normalized name #216

**Comment by VadymvUA-FIN** [comment]
Hi, please link for download client v. 0.3.0 =)
Thank you! =)

**Comment by j-chmielewski** [comment]
v0.3.0 released: https://github.com/DefGuard/client/releases/tag/v0.3.0
