### ISSUE TITLE
DefGuard Client totally halted in windows

### ISSUE THREAD

**Issue by DarKidoz** [DefGuard/client#240]
After sometimes use, the client totally not working, no response even connect button was clicked. After several times of reboot, internet was not working anymore, tried to connect different WiFi or Ethernet connection also not working. To solve this issue, we need to remove DefGuard-client, WireGuard and reboot the pc to solve the internet connection. 

The DefGuard-client need to reinstall to work again, but not sure the problem will occur again.

**Comment by teon** [comment]
@kevinmagni We have released a 1.0.0 client with **a lot of bug fixes** - that should fix all issues you had.
