### ISSUE TITLE
Ubuntu 22.04: reload returns a blank window

### ISSUE THREAD

**Issue by Kevin-Thierry-Scaleflex** [DefGuard/client#246]
### How to reproduce
Right click on one of the VPN configuration on the left and click "Reload".

### Result
The whole window becomes blank. Hiding the window and showing it again still returns a blank window.

### Version
0.3.0

### Errors when reloading
```
Asset `client/instance` not found; fallback to client/instance.html
Asset `client/assets/index-23b058b6.js` not found; fallback to client/assets/index-23b058b6.js.html
Asset `client/assets/index-ddbbbd84.css` not found; fallback to client/assets/index-ddbbbd84.css.html
```

**Comment by teon** [comment]
Fixed in 0.5.0
