### ISSUE TITLE
Cannot reopen after closed on mac book air with apple m2 chip

### ISSUE THREAD

**Issue by jearton** [DefGuard/client#251]
I should force to exit the app if I want to reopen it, but that means all connections are disconnected.

**Comment by filiprafaj** [comment]
I experience the same on debian 12

**Comment by teon** [comment]
@filiprafaj @jearton most probably you are experiencing a different bug (or a lack of feature). If you close the app it's not actually closed - its running and can be open / shown from the tray menu (there is an icon there).

We have fixed that in upcomming 0.5 release with #257
