### ISSUE TITLE
Wireguard-go binaries for aarch64-apple-darwin

### ISSUE THREAD

**Issue by cpprian** [DefGuard/client#253]
Can't build application using `pnpm tauri build`, because there is no wireguard-go binaries in path: `src-tauri/resources-macos/binaries`.

Things to do:
- [ ] add install.sh for building manually wireguard-go on macOS
- [ ] update README 
- [ ] update gitbook doc

**Comment by cpprian** [comment]
https://github.com/DefGuard/client/pull/67

**Comment by Nthalk** [comment]
Any basic instructions to do this? The MFA on OSX aarch64 is currently busted (worked last night, same install, restarted, and now I get "Could not start MFA process. Please try again or contact administrator." when selecting "Authenticator App").

Trying to debug the error, however, I cannot start the app without the "  path matching resources-macos/binaries/*-aarch64-apple-darwin not found." error.

Googling around, I couldn't find good instructions on how to even build these.

**Comment by teon** [comment]
Fixed in 1.0.1
