### ISSUE TITLE
Used already activated

### ISSUE THREAD

**Issue by Coedgy** [DefGuard/client#254]
When trying to add instance on an already activated account, the client want's me to set up passwords and such, which leads to an unexpected error. On the proxy servers' logs it shows that the device was added successfully, but then it tries to activate user which leads to the error. 

I assume it should only ask me for instance URL, token and device name? The device does get added, but the client doesn't show the instance as it gets stuck on the enrollment.

**Comment by teon** [comment]
@Coedgy can you specify what versions of core, proxy & client do you use?
Did you test on latest?

**Comment by Coedgy** [comment]
> @Coedgy can you specify what versions of core, proxy & client do you use?
> Did you test on latest?

All on latest.

**Comment by teon** [comment]
@Coedgy We have reproduced the error - and it's only possible when you have an outdated proxy. Please double check if you have proxy 0.5.1 actually running.
If you have, please reopen this issue and post your logs from core & proxy of this error during the desktop client activation poroces.
