### ISSUE TITLE
Windows Installer not working

### ISSUE THREAD

**Issue by enb-f** [DefGuard/client#276]
[defguard-client_0.4.0_x64_en-US.exe](https://github.com/DefGuard/client/releases/download/v0.4.0/defguard-client_0.4.0_x64_en-US.exe)

The installer for the latest release of the desktop application does not work, after downloading and running nothing happens.
OS: Windows 11 23H2 (10.0.22631)

**Comment by teon** [comment]
@enb-f try tu run the installer as administrator.

**Comment by enb-f** [comment]
> @enb-f try tu run the installer as administrator.

it doesn't help, the result is the same, I tried it on a computer with Windows Server 2019, the problem is the same
