### ISSUE TITLE
Wireguard and restart OS

### ISSUE THREAD

**Issue by ajtak-angelus** [DefGuard/client#285]
Please add a setting for WG tunnels to not automatically reconnect after OS restart. When I currently restart Windows, the GUI pretends that WG is not running, but it is actually connected. Thank you very much

**Comment by teon** [comment]
This should be fixed: https://github.com/DefGuard/client/issues/194
We will publish 0.5.0 soon with the fix.

**Comment by ajtak-angelus** [comment]
Please add an option for each WG tunnel to automatically reestablish itself after a reboot.
