### ISSUE TITLE
Hide defguard-client icon from taskbar on macOS

### ISSUE THREAD

**Issue by pravic** [DefGuard/client#326]
Currently, the defguard client is displayed in the system tray and in the taskbar.

Albeit, the taskbar icon does nothing when you click on it (the tray icon shows/hides the main window on click).

Please, remove/hide the taskbar icon like OpenVPN does (and other network service applications).

OS: macOS 14.6.1
Client: 0.4.0

**Comment by pravic** [comment]
Also relates to https://github.com/DefGuard/client/issues/282.

**Comment by teon** [comment]
This is already fixed in upcoming 0.5.0 release
