### ISSUE TITLE
Desktop Client VPN details

### ISSUE THREAD

**Issue by teon** [DefGuard/client#75]
We need a way to see in the VPN location (when connected):
1. VPN logs (and Copy button)
2. Settings that were sent by defguard - DNS, Allowed IPs list

**Comment by teon** [comment]
@wojcik91 can you add to the **service** what version it is on startup?

**Comment by wojcik91** [comment]
@teon Could you please elaborate on what you'd like to see? 

I should probably note that the service is currently NOT versioned separately from the client, so service version = client version.

**Comment by teon** [comment]
@filipslezaklab changing from teting->in progress - no way to test (no releases/builds)

**Comment by filipslezaklab** [comment]
@teon We postponed testing for that task until tunnels functionality is done.

**Comment by teon** [comment]
- the chart is broken and to large
- logs are not showing
